INSERT INTO `item` (`id`, `created_at`, `updated_at`, `code`, `description`, `price`, `unit_of_measure_id`) VALUES 
(1, CURRENT_TIME(), CURRENT_TIME(), 'AAA', 'legno', '10',  2),
(2, CURRENT_TIME(), CURRENT_TIME(), 'BBB', 'roccia', '20',  2),
(3, CURRENT_TIME(), CURRENT_TIME(), 'CCC', 'acqua', '30',  4),
(4, CURRENT_TIME(), CURRENT_TIME(), 'DDD', 'pietra', '40',  2),
(5, CURRENT_TIME(), CURRENT_TIME(), 'EEE', 'fango', '50',  2),
(6, CURRENT_TIME(), CURRENT_TIME(), 'FFF', 'sabbia', '60',  2),
(7, CURRENT_TIME(), CURRENT_TIME(), 'GGG', 'veleno', '70',  3),
(8, CURRENT_TIME(), CURRENT_TIME(), 'HHH', 'rete', '80',  5),
(9, CURRENT_TIME(), CURRENT_TIME(), 'III', 'bronzo', '90',  1),
(10, CURRENT_TIME(), CURRENT_TIME(), 'JJJ', 'oro', '100',  1),
(11, CURRENT_TIME(), CURRENT_TIME(), 'KKK', 'spago', '110',  5),
(12, CURRENT_TIME(), CURRENT_TIME(), 'LLL', 'cavo', '120',  6),
(13, CURRENT_TIME(), CURRENT_TIME(), 'MMM', 'granito', '130',  5),
(14, CURRENT_TIME(), CURRENT_TIME(), 'NNN', 'marmo', '140',  1),
(15, CURRENT_TIME(), CURRENT_TIME(), 'OOO', 'diluente', '150',  4)